GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/654096665b0ffdde458a121a

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Ari",
    "subscribedToChannel": "Nat" 
}

###

DELETE http://localhost:3000/subscribers/654099c70ec3ef1692affc28

###

PATCH http://localhost:3000/subscribers/654099b50ec3ef1692affc26
Content-Type: application/json

{
    "name": "Rey",
    "subscribedToChannel": "Hector" 
}